# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bloomfilter}
  s.version = "1.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Grigorik", "Tatsuya Mori"]
  s.date = %q{2010-08-25}
  s.description = %q{Counting Bloom Filter implemented in Ruby}
  s.email = %q{ilya@igvita.com}
  s.extensions = ["ext/cbloomfilter/extconf.rb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bloomfilter.gemspec",
     "examples/bf.rb",
     "examples/redis-backed.rb",
     "examples/simple.rb",
     "ext/cbloomfilter/cbloomfilter.c",
     "ext/cbloomfilter/crc32.c",
     "ext/cbloomfilter/crc32.h",
     "ext/cbloomfilter/extconf.rb",
     "lib/bloomfilter.rb",
     "lib/redisbloom.rb",
     "spec/c_spec.rb",
     "spec/helper.rb",
     "spec/redis_spec.rb",
     "spec/spec.opts"
  ]
  s.homepage = %q{http://github.com/igrigorik/bloomfilter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{bloomfilter}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Counting Bloom Filter implemented in Ruby}
  s.test_files = [
    "spec/c_spec.rb",
     "spec/helper.rb",
     "spec/redis_spec.rb",
     "examples/bf.rb",
     "examples/redis-backed.rb",
     "examples/simple.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rake-compiler>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rake-compiler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rake-compiler>, [">= 0"])
  end
end

